env:
    env: prod
    
database:
    driver: pdo_mysql
    host: 127.0.0.1
    dbname: db_test
    user: root
    password: 
    #memory: true #pour sqlite in memory (rapide !)

swiftmailer:
   host: host
   port: 25
   username: username
   password: password
   encryption: null
   auth_mode: null